# Generated by Django 3.2.4 on 2021-06-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='bestsellers_image', verbose_name='Shekili')),
                ('price', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HomeBestSeller',
                'verbose_name_plural': 'HomeBestSellers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MenViewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='viewproducts_image', verbose_name='Shekili')),
                ('price', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MenViewProduct',
                'verbose_name_plural': 'MenViewProducts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('yazili', models.CharField(max_length=127, null=True, verbose_name='Yazili')),
                ('image', models.ImageField(upload_to='slider_image', verbose_name='Shekili')),
                ('abc', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
                ('text2', models.CharField(max_length=127, null=True, verbose_name='Text2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ('-created_at',),
            },
        ),
    ]
