# Generated by Django 3.2.3 on 2021-06-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='price',
            field=models.CharField(max_length=127, null=True, verbose_name='Qiymet hissesi'),
        ),
        migrations.AddField(
            model_name='slider',
            name='text2',
            field=models.CharField(max_length=127, null=True, verbose_name='Text2'),
        ),
        migrations.AddField(
            model_name='slider',
            name='yazili',
            field=models.CharField(max_length=127, null=True, verbose_name='Yazili'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
    ]
