# Generated by Django 3.2.4 on 2021-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homebestsellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenViewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='viewproducts_image', verbose_name='Shekili')),
                ('price', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
            ],
        ),
    ]
