# Generated by Django 3.2.3 on 2021-06-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210625_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
