# Generated by Django 3.2.3 on 2021-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210625_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='img',
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=11, upload_to='slider_image', verbose_name='Shekil'),
            preserve_default=False,
        ),
    ]
