# Generated by Django 3.2.3 on 2021-06-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210625_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='price',
            field=models.CharField(max_length=127, verbose_name='Qiymet hissesi'),
        ),
    ]
