# Generated by Django 3.2.3 on 2021-06-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_slider_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
    ]
