# Generated by Django 3.2.3 on 2021-06-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=18, upload_to='slider_image', verbose_name='Shekili'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
