# Generated by Django 3.2.3 on 2021-06-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210625_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
    ]
