# Generated by Django 3.2.3 on 2021-06-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=11, upload_to='slider_image', verbose_name='Shekili'),
            preserve_default=False,
        ),
    ]
