# Generated by Django 3.2.3 on 2021-06-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
    ]
