# Generated by Django 3.2.3 on 2021-06-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_slider_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
