# Generated by Django 3.2.3 on 2021-06-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0013_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('yazili', models.CharField(max_length=127, null=True, verbose_name='Yazili')),
                ('price', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
                ('text2', models.CharField(max_length=127, null=True, verbose_name='Text2')),
            ],
        ),
    ]
