# Generated by Django 3.2.4 on 2021-06-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, null=True, verbose_name='Name')),
                ('surname', models.CharField(max_length=127, null=True, verbose_name='Surname')),
                ('number', models.CharField(max_length=127, verbose_name='Number')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('-created_at',),
            },
        ),
    ]
