# Generated by Django 3.2.3 on 2021-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kurs adini yaz:', max_length=127, unique=True, verbose_name='Kurs adi')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='courses/default_course_image.jpg', upload_to='')),
                ('date', models.DateField(auto_now=True)),
                ('avaibable', models.BooleanField(default=True)),
            ],
        ),
    ]
