# Generated by Django 3.2.5 on 2021-07-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('yazili', models.CharField(max_length=127, null=True, verbose_name='Yazili')),
                ('image', models.ImageField(upload_to='slider_image', verbose_name='Shekili')),
                ('abc', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
                ('text2', models.CharField(max_length=127, null=True, verbose_name='Text2')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
