# Generated by Django 3.2.3 on 2021-07-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='about_image', verbose_name='Shekili')),
                ('text', models.TextField(null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='cart_image', verbose_name='Shekili')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('price', models.CharField(max_length=127, null=True, verbose_name='PRICE')),
                ('quantity', models.CharField(max_length=127, null=True, verbose_name='QUANTITY')),
                ('total', models.CharField(max_length=127, null=True, verbose_name='TOTAL')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, null=True, verbose_name='Name')),
                ('surname', models.CharField(max_length=127, null=True, verbose_name='Surname')),
                ('number', models.CharField(max_length=127, verbose_name='Number')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('message', models.TextField(null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='bestsellers_image', verbose_name='Shekili')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
            },
        ),
        migrations.CreateModel(
            name='HomeBestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='bestsellers_image', verbose_name='Shekili')),
                ('price', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
            ],
            options={
                'verbose_name': 'HomeBestSeller',
                'verbose_name_plural': 'HomeBestSellers',
            },
        ),
        migrations.CreateModel(
            name='MenShopNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='menshopnows_image', verbose_name='Shekili')),
            ],
            options={
                'verbose_name': 'MenShopNow',
                'verbose_name_plural': 'MenShopNow',
            },
        ),
        migrations.CreateModel(
            name='MenSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='mensliders_image', verbose_name='Shekili')),
            ],
            options={
                'verbose_name': 'MenSlider',
                'verbose_name_plural': 'MenSliders',
            },
        ),
        migrations.CreateModel(
            name='MenViewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='viewproducts_image', verbose_name='Shekili')),
                ('price', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
            ],
            options={
                'verbose_name': 'MenViewProduct',
                'verbose_name_plural': 'MenViewProducts',
            },
        ),
        migrations.CreateModel(
            name='TrustedPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='trustedpartners_image', verbose_name='Shekili')),
                ('price', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
            ],
            options={
                'verbose_name': 'TrustedPartner',
                'verbose_name_plural': 'TrustedPartners',
            },
        ),
        migrations.CreateModel(
            name='WomenShopNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='womenshopnows_image', verbose_name='Shekili')),
            ],
            options={
                'verbose_name': 'WomenShopNow',
                'verbose_name_plural': 'WomenShopNow',
            },
        ),
        migrations.CreateModel(
            name='WomenSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='womensliders_image', verbose_name='Shekili')),
            ],
            options={
                'verbose_name': 'WomenSlider',
                'verbose_name_plural': 'WomenSliders',
            },
        ),
    ]
