# Generated by Django 3.2.3 on 2021-07-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='surname',
        ),
    ]
