# Generated by Django 3.2.3 on 2021-07-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_subject_contact_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='cartrelated_image', verbose_name='Shekili')),
                ('price', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
            ],
            options={
                'verbose_name': 'CartRelated',
                'verbose_name_plural': 'CartRelateds',
            },
        ),
    ]
