# Generated by Django 3.2.3 on 2021-07-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prooduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='product_image', verbose_name='Shekili')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('price', models.CharField(max_length=127, null=True, verbose_name='PRICE')),
                ('quantity', models.CharField(max_length=127, null=True, verbose_name='QUANTITY')),
                ('total', models.CharField(max_length=127, null=True, verbose_name='TOTAL')),
            ],
            options={
                'verbose_name': 'Prooduct ',
                'verbose_name_plural': 'Prooducts',
            },
        ),
        migrations.CreateModel(
            name='ShopMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='shopmore_image', verbose_name='Shekili')),
                ('price', models.CharField(max_length=127, verbose_name='Qiymet hissesi')),
            ],
            options={
                'verbose_name': 'ShopMore',
                'verbose_name_plural': 'ShopMores',
            },
        ),
    ]
