# Generated by Django 3.2.3 on 2021-07-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_prooduct_shopmore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prooduct',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product ', 'verbose_name_plural': 'Products'},
        ),
    ]
