# Generated by Django 3.2.3 on 2021-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('text01', models.CharField(max_length=127, null=True, verbose_name='Text01')),
                ('text02', models.CharField(max_length=127, null=True, verbose_name='Text02')),
                ('text03', models.CharField(max_length=127, null=True, verbose_name='Text03')),
                ('text04', models.CharField(max_length=127, null=True, verbose_name='Text04')),
                ('text05', models.CharField(max_length=127, null=True, verbose_name='Text05')),
                ('text06', models.CharField(max_length=127, null=True, verbose_name='Text06')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Write',
                'verbose_name_plural': 'Writes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ('-created_at',), 'verbose_name': 'Home', 'verbose_name_plural': 'Homes'},
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(upload_to='home_image', verbose_name='Shekili'),
        ),
    ]
